# Generated by Django 3.0.3 on 2020-08-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Venue Name')),
                ('photo', models.CharField(max_length=32, verbose_name='Venue photo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': 'attendee', 'verbose_name_plural': 'attendees'},
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_token', models.CharField(max_length=64, verbose_name='attendee_token')),
                ('selected_time', models.DateTimeField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext2020.Venue')),
            ],
        ),
    ]
