# Generated by Django 3.0.7 on 2020-08-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': 'attendee', 'verbose_name_plural': 'attendees'},
        ),
    ]
