# Generated by Django 3.0.3 on 2020-08-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0002_auto_20200820_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='selected_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
