# Generated by Django 3.0.3 on 2020-08-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0003_auto_20200822_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='photo',
            field=models.CharField(max_length=128, verbose_name='Venue photo'),
        ),
    ]
