# Generated by Django 3.0.3 on 2020-08-24 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0002_auto_20200822_1030'),
        ('ext2020', '0004_auto_20200824_1029'),
    ]

    operations = [
    ]
