# Generated by Django 3.0.3 on 2020-08-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0006_auto_20200824_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='attendee_token',
        ),
        migrations.AddField(
            model_name='choice',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ext2020.Attendee'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='photo',
            field=models.CharField(blank=True, max_length=128, verbose_name='Venue photo'),
        ),
    ]
