# Generated by Django 3.0.3 on 2020-08-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0047_auto_20200630_2342'),
        ('ext2020', '0007_auto_20200824_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTrackEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.TalkProposal')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext2020.Venue')),
            ],
        ),
    ]
