# Generated by Django 3.0.3 on 2020-08-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0008_communitytrackevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytrackevent',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
