# Generated by Django 3.0.3 on 2020-08-24 07:25

import core.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0047_auto_20200630_2342'),
        ('ext2020', '0009_communitytrackevent_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytrackevent',
            name='talk',
            field=core.models.BigForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.TalkProposal'),
        ),
    ]
