# Generated by Django 3.0.3 on 2020-08-28 06:51

import core.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_joblistingsevent'),
        ('proposals', '0047_auto_20200630_2342'),
        ('ext2020', '0010_auto_20200824_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'community track choice', 'verbose_name_plural': 'community track choices'},
        ),
        migrations.AlterModelOptions(
            name='communitytrackevent',
            options={'ordering': ['order'], 'verbose_name': 'community track event', 'verbose_name_plural': 'community track events'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'community track venue', 'verbose_name_plural': 'community track venues'},
        ),
        migrations.AddField(
            model_name='communitytrackevent',
            name='sponsored_event',
            field=core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.SponsoredEvent'),
        ),
        migrations.AlterField(
            model_name='communitytrackevent',
            name='talk',
            field=core.models.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.TalkProposal'),
        ),
    ]
