# Generated by Django 3.0.7 on 2020-09-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ext2020', '0012_auto_20200828_1514'),
        ('events', '0029_auto_20200902_1549'),
        ('events', '0027_auto_20200829_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytrackevent',
            name='begin_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begined_communitytrackevent_set', to='events.Time', verbose_name='begin time'),
        ),
        migrations.AddField(
            model_name='communitytrackevent',
            name='end_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ended_communitytrackevent_set', to='events.Time', verbose_name='end time'),
        ),
        migrations.AlterModelOptions(
            name='communitytrackevent',
            options={'ordering': ['begin_time', 'order'], 'verbose_name': 'community track event', 'verbose_name_plural': 'community track events'},
        ),
        migrations.AlterField(
            model_name='communitytrackevent',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ext2020.Venue'),
        ),
        migrations.AddField(
            model_name='communitytrackevent',
            name='custom_event',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='communitytrackevent',
            name='custom_event_en_us',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='communitytrackevent',
            name='custom_event_zh_hant',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='communitytrackevent',
            name='begin_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beginning_communitytrackevent_set', to='events.Time', verbose_name='begin time'),
        ),
        migrations.AlterField(
            model_name='communitytrackevent',
            name='end_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_communitytrackevent_set', to='events.Time', verbose_name='end time'),
        ),
    ]
