# Generated by Django 3.0.7 on 2020-09-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0013_auto_20200901_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitytrackevent',
            options={'ordering': ['begin_time', 'order'], 'verbose_name': 'community track event', 'verbose_name_plural': 'community track events'},
        ),
        migrations.AlterField(
            model_name='communitytrackevent',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ext2020.Venue'),
        ),
    ]
