# Generated by Django 3.0.7 on 2020-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0014_auto_20200901_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytrackevent',
            name='custom_event',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
