# Generated by Django 3.0.7 on 2020-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext2020', '0015_communitytrackevent_custom_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytrackevent',
            name='custom_event_en_us',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='communitytrackevent',
            name='custom_event_zh_hant',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
