from rest_framework import viewsets
from rest_framework.pagination import LimitOffsetPagination

from events import models
from events import serializers

class TalkProposalViewSet(viewsets.ModelViewSet):
    queryset = models.TalkProposal.objects.all()
    serializer_class = serializers.TalkProposalListSerializer

    def list(self, request, *args, **kwargs):
        """

[
    {
        "id": 1,
        "conference": "pycontw-2021",
        "title": "ABC",
        "category": "FIN",
        "language": "ZHEN",
        "abstract": "ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA",
        "python_level": "INTERMEDIATE",
        "detailed_description": "",
        "recording_policy": true,
        "live_stream_policy": true,
        "referring_policy": false,
        "slide_link": "",
        "slido_embed_link": "",
        "created_at": "2021-02-27T14:51:16.722488+08:00",
        "last_updated_at": "2021-02-27T14:51:45.834508+08:00",
        "remoting_policy": false,
        "outline": "",
        "objective": "ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA",
        "supplementary": "",
        "cancelled": false,
        "accepted": null,
        "labels": "",
        "duration": "PREF30",
        "first_time_speaker": false,
        "submitter": 2
    }
]
        """


        """
        {
            "title": "string",
            "category": "string",
            "language": "string",
            "python_level": "string",
            "recording_policy": "string",
            "abstract": "string",
            "detailed_description": "string",
            "slide_link": "string",
            "slido_embed_link": "string",
            "sponsored": true,
            "speakers": [
                {
                    "thumbnail_url": "string",
                    "name": "string",
                    "github_profile_url": "string",
                    "twitter_profile_url": "string",
                    "facebook_profile_url": "string"
                }
            ]
        }
        """
        response = super().list(request, *args, **kwargs)

        return response

