# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import sponsors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('website_url', models.URLField(blank=True, max_length=255, verbose_name='website URL')),
                ('intro', models.TextField(verbose_name='Introduction')),
                ('logo', models.ImageField(upload_to=sponsors.models.logo_upload_to, verbose_name='logo')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'platinum sponsor'), (1, 'gold sponsor'), (2, 'silver sponsor'), (3, 'bronze sponsor'), (4, 'special sponsor')], verbose_name='level')),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsors',
            },
        ),
    ]
