# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='intro_en_us',
            field=models.TextField(null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='intro_zh_hant',
            field=models.TextField(null=True, verbose_name='Introduction'),
        ),
    ]
