# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-01 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20160427_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('level', 'name'), 'verbose_name': 'sponsor', 'verbose_name_plural': 'sponsors'},
        ),
    ]
