# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_auto_20160530_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='conference',
            field=models.SlugField(default='pycontw-2016', verbose_name='conference'),
            preserve_default=False,
        ),
    ]
