# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_sponsor_conference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='logo',
            new_name='logo_image',
        ),
    ]
