# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import sponsors.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0007_rename_sponsor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo_svg',
            field=models.FileField(blank=True, help_text='Vector format of the logo, in SVG. This takes precedence to the raster format, if available.', upload_to=sponsors.models.logo_upload_to, verbose_name='logo (SVG)'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='intro',
            field=models.TextField(verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='intro_en_us',
            field=models.TextField(null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='intro_zh_hant',
            field=models.TextField(null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo_image',
            field=models.ImageField(help_text='Raster format of the logo, e.g. PNG, JPEG. This is used as fallback when the SVG file is not available.', upload_to=sponsors.models.logo_upload_to, verbose_name='logo (image)'),
        ),
    ]
