# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import sponsors.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0008_add_svg_field_and_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Raster format of the logo, e.g. PNG, JPEG. This is used as fallback when the SVG file is not available.', upload_to=sponsors.models.logo_upload_to, verbose_name='logo (image)'),
        ),
    ]
