# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0011_auto_20170503_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.SmallIntegerField(choices=[(-1, 'organizer'), (0, 'co-organizer'), (1, 'platinum'), (2, 'gold'), (3, 'silver'), (4, 'bronze'), (5, 'special')], verbose_name='level'),
        ),
    ]
