# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-08 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0013_auto_20180305_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'platinum'), (2, 'gold'), (3, 'silver'), (4, 'bronze'), (5, 'special'), (6, 'organizer'), (7, 'co-organizer')], verbose_name='level'),
        ),
    ]
