# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0015_auto_20190425_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
