# Generated by Django 3.0.3 on 2020-02-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0016_auto_20200223_1659'),
        ('sponsors', '0016_auto_20200223_2331'),
    ]

    operations = [
    ]
