# Generated by Django 3.0.7 on 2021-02-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0021_auto_20210201_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='openrole',
            name='description_en_us',
            field=models.TextField(null=True, verbose_name='open role descsription'),
        ),
        migrations.AddField(
            model_name='openrole',
            name='description_zh_hant',
            field=models.TextField(null=True, verbose_name='open role descsription'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='intro_en_us',
            field=models.TextField(null=True, verbose_name='introduction'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='intro_zh_hant',
            field=models.TextField(null=True, verbose_name='introduction'),
        ),
    ]
