# Generated by Django 3.0.7 on 2021-03-11 03:12

from django.db import migrations, models
import sponsors.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0022_auto_20210203_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo_image',
            field=models.ImageField(blank=True, db_column='logo', help_text='Raster format of the logo, e.g. PNG, JPEG. This is used as fallback when the SVG file is not available.', storage=sponsors.models.select_storage, upload_to=sponsors.models.logo_upload_to, verbose_name='logo (image)'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo_svg',
            field=models.FileField(blank=True, help_text='Vector format of the logo, in SVG. This takes precedence to the raster format, if available.', storage=sponsors.models.select_storage, upload_to=sponsors.models.logo_upload_to, verbose_name='logo (SVG)'),
        ),
    ]
