# Generated by Django 3.1.7 on 2021-04-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0023_auto_20210311_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='subtitle',
            field=models.TextField(null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='subtitle_en_us',
            field=models.TextField(null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='subtitle_zh_hant',
            field=models.TextField(null=True, verbose_name='subtitle'),
        ),
    ]
