# Generated by Django 3.1.7 on 2021-07-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0025_auto_20210426_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='name_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='subtitle_en_us',
            field=models.TextField(blank=True, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='subtitle_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='subtitle'),
        ),
    ]
