# Generated by Django 3.1.7 on 2022-07-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0027_auto_20220227_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Enter a positive number to represent your orders, or it will be a null.', null=True, verbose_name='order'),
        ),
    ]
