# Generated by Django 3.1.7 on 2022-08-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0028_sponsor_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'platinum'), (2, 'gold'), (3, 'silver'), (4, 'bronze'), (5, 'special'), (6, 'special-thanks'), (7, 'organizer'), (8, 'co-organizer')], verbose_name='level'),
        ),
    ]
