# Generated by Django 3.1.7 on 2023-03-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0030_remove_pre_recorded_policy_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openrole',
            options={'verbose_name': 'open role', 'verbose_name_plural': 'open roles'},
        ),
        migrations.AlterField(
            model_name='openrole',
            name='description',
            field=models.TextField(verbose_name='open role description'),
        ),
        migrations.AlterField(
            model_name='openrole',
            name='description_en_us',
            field=models.TextField(null=True, verbose_name='open role description'),
        ),
        migrations.AlterField(
            model_name='openrole',
            name='description_zh_hant',
            field=models.TextField(null=True, verbose_name='open role description'),
        ),
    ]
