# Generated by Django 3.2.25 on 2024-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0031_auto_20240127_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openrole',
            options={'verbose_name': 'open role', 'verbose_name_plural': 'open roles'},
        ),
        migrations.AlterField(
            model_name='openrole',
            name='description',
            field=models.TextField(verbose_name='open role description'),
        ),
        migrations.AlterField(
            model_name='openrole',
            name='description_en_us',
            field=models.TextField(null=True, verbose_name='open role description'),
        ),
        migrations.AlterField(
            model_name='openrole',
            name='description_zh_hant',
            field=models.TextField(null=True, verbose_name='open role description'),
        ),
    ]
