# Generated by Django 3.2.25 on 2025-03-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0034_alter_sponsor_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openrole',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020'), ('pycontw-2021', 'PyCon Taiwan 2021'), ('pycontw-2022', 'PyCon Taiwan 2022'), ('pycontw-2023', 'PyCon Taiwan 2023'), ('pycontw-2024', 'PyCon Taiwan 2024'), ('pycontw-2025', 'PyCon Taiwan 2025')], default='pycontw-2025', verbose_name='conference'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020'), ('pycontw-2021', 'PyCon Taiwan 2021'), ('pycontw-2022', 'PyCon Taiwan 2022'), ('pycontw-2023', 'PyCon Taiwan 2023'), ('pycontw-2024', 'PyCon Taiwan 2024'), ('pycontw-2025', 'PyCon Taiwan 2025')], default='pycontw-2025', verbose_name='conference'),
        ),
    ]
