# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_tutorialproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='objective',
            field=models.TextField(default='Please UPDATE this field.', help_text="What will the attendees get out of your talk? When they leave theroom, what will they learn that they didn't know before?", max_length=500, verbose_name='objective'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='objective',
            field=models.TextField(default='Please UPDATE this field.', help_text="What will the attendees get out of your talk? When they leave theroom, what will they learn that they didn't know before?", max_length=500, verbose_name='objective'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='abstract',
            field=models.TextField(help_text='The overview of what the talk is about. If the talk assume some domain knowledge please state it here. If your talk is accepted, this will be displayed on both the website and the handbook. Should be one paragraph.', max_length=500, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='category',
            field=models.CharField(choices=[('PRAC', 'Best Practices & Patterns'), ('COM', 'Community'), ('DB', 'Databases'), ('DATA', 'Data Analysis'), ('EDU', 'Education'), ('EMBED', 'Embedded Systems'), ('GAME', 'Gaming'), ('OTHER', 'Other'), ('CORE', 'Python Core & Internals (language, stdlib, etc.)'), ('LIBS', 'Python Libraries'), ('SCI', 'Science'), ('SEC', 'Security'), ('ADMIN', 'Systems Administration'), ('TEST', 'Testing'), ('WEB', 'Web Frameworks')], max_length=5, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='detailed_description',
            field=models.TextField(blank=True, help_text="Try not be too lengthy to scare away reviewers or potential audience. A comfortable length is less than 1000 chars (about 600 Chinese characters). Since most reviewers may not understand the topic as deep as you do, including related links to the talk topic will help reviewers understand the proposal. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='outline',
            field=models.TextField(blank=True, help_text='How the talk will be arranged. It is highly recommended to attach the estimated time length for each sections in the talk. Talks in favor of 45min should have a fallback plan about how to shrink thecontent into a 25min one.', verbose_name='outline'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='python_level',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('EXPERIENCED', 'Experienced')], help_text='The choice of talk level matters during the review process. More definition of talk level can be found at the Talk Level Definition in [How to Propose a talk] page. Note that a proposal won\'t be more likely to be accepted because of being "Novice" level. We may contact you to change the talk level when we find the content is too-hard or too-easy for the target audience.', max_length=12, verbose_name='python level'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='abstract',
            field=models.TextField(help_text='The overview of what the talk is about. If the talk assume some domain knowledge please state it here. If your talk is accepted, this will be displayed on both the website and the handbook. Should be one paragraph.', max_length=500, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='category',
            field=models.CharField(choices=[('PRAC', 'Best Practices & Patterns'), ('COM', 'Community'), ('DB', 'Databases'), ('DATA', 'Data Analysis'), ('EDU', 'Education'), ('EMBED', 'Embedded Systems'), ('GAME', 'Gaming'), ('OTHER', 'Other'), ('CORE', 'Python Core & Internals (language, stdlib, etc.)'), ('LIBS', 'Python Libraries'), ('SCI', 'Science'), ('SEC', 'Security'), ('ADMIN', 'Systems Administration'), ('TEST', 'Testing'), ('WEB', 'Web Frameworks')], max_length=5, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='detailed_description',
            field=models.TextField(blank=True, help_text="Try not be too lengthy to scare away reviewers or potential audience. A comfortable length is less than 1000 chars (about 600 Chinese characters). Since most reviewers may not understand the topic as deep as you do, including related links to the talk topic will help reviewers understand the proposal. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='outline',
            field=models.TextField(blank=True, help_text='How the talk will be arranged. It is highly recommended to attach the estimated time length for each sections in the talk. Talks in favor of 45min should have a fallback plan about how to shrink thecontent into a 25min one.', verbose_name='outline'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='python_level',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('EXPERIENCED', 'Experienced')], help_text='The choice of talk level matters during the review process. More definition of talk level can be found at the Talk Level Definition in [How to Propose a talk] page. Note that a proposal won\'t be more likely to be accepted because of being "Novice" level. We may contact you to change the talk level when we find the content is too-hard or too-easy for the target audience.', max_length=12, verbose_name='python level'),
        ),
    ]
