# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_auto_20151220_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialproposal',
            name='duration',
            field=models.CharField(choices=[('HALFDAY', 'Half day'), ('FULLDAY', 'Full day')], default='FULLDAY', max_length=7, verbose_name='duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='outline',
            field=models.TextField(blank=True, help_text='How the talk will be arranged. It is highly recommended to attach the estimated time length for each sections in the talk. Talks in favor of 45min should have a fallback plan about how to shrink the content into a 25min one.', verbose_name='outline'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='python_level',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('EXPERIENCED', 'Experienced')], help_text='The choice of talk level matters during the review process. More definition of talk level can be found at the <a href="/speaking/talk/" target="_blank">How to Propose a talk</a> page. Note that a proposal won\'t be more likely to be accepted because of being "Novice" level. We may contact you to change the talk level when we find the content is too-hard or too-easy for the target audience.', max_length=12, verbose_name='python level'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='outline',
            field=models.TextField(blank=True, help_text='How the tutorial will be arranged. You should enumerate over each section in your talk and attach each section with the estimated time length.', verbose_name='outline'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='python_level',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('EXPERIENCED', 'Experienced')], help_text='The choice of talk level matters during the review process. More definition of talk level can be found at the <a href="/speaking/talk/" target="_blank">How to Propose a talk</a> page. Note that a proposal won\'t be more likely to be accepted because of being "Novice" level. We may contact you to change the talk level when we find the content is too-hard or too-easy for the target audience.', max_length=12, verbose_name='python level'),
        ),
    ]
