# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_auto_20151221_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='detailed_description',
            field=models.TextField(blank=True, help_text="Try not be too lengthy to scare away reviewers or potential audience. A comfortable length is less than 1000 characters (or about 600 Chinese characters). Since most reviewers may not understand the topic as deep as you do, including related links to the talk topic will help reviewers understand the proposal. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='objective',
            field=models.TextField(help_text="What will the attendees get out of your talk? When they leave the room, what will they learn that they didn't know before?", max_length=500, verbose_name='objective'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='detailed_description',
            field=models.TextField(blank=True, help_text="Try not be too lengthy to scare away reviewers or potential audience. A comfortable length is less than 1000 characters (or about 600 Chinese characters). Since most reviewers may not understand the topic as deep as you do, including related links to the talk topic will help reviewers understand the proposal. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='objective',
            field=models.TextField(help_text="What will the attendees get out of your talk? When they leave the room, what will they learn that they didn't know before?", max_length=500, verbose_name='objective'),
        ),
    ]
