# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_auto_20151222_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='cancelled'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='cancelled'),
        ),
    ]
