# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:58
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_auto_20151229_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalspeaker',
            name='user',
            field=core.models.BigForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='submitter',
            field=core.models.BigForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='submitter'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='submitter',
            field=core.models.BigForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='submitter'),
        ),
    ]
