# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_auto_20160102_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkproposal',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='tutorialproposal',
            name='target_audience',
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='objective',
            field=models.TextField(help_text='Who is the intended audience for your talk? (Be specific, "Python users" is not a good answer). And what will the attendees get out of your talk? When they leave the room, what will they learn that they didn\'t know before?', max_length=500, verbose_name='objective'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='objective',
            field=models.TextField(help_text='Who is the intended audience for your talk? (Be specific, "Python users" is not a good answer). And what will the attendees get out of your talk? When they leave the room, what will they learn that they didn\'t know before?', max_length=500, verbose_name='objective'),
        ),
    ]
