# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_auto_20160122_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='recording_policy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text="Whether you agree to give permission to PyCon Taiwan to record, edit, and release audio and video of your presentation. More information can be found at <a href='/None/speaking/recording/' target='_blank'>Recording Release</a> page.", verbose_name='recording policy'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='recording_policy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text="Whether you agree to give permission to PyCon Taiwan to record, edit, and release audio and video of your presentation. More information can be found at <a href='/None/speaking/recording/' target='_blank'>Recording Release</a> page.", verbose_name='recording policy'),
        ),
    ]
