# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 07:09
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_auto_20160202_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='abstract',
            field=core.models.EAWTextField(help_text='The overview of what the talk is about. If the talk assume some domain knowledge please state it here. If your talk is accepted, this will be displayed on both the website and the handbook. Should be one paragraph.', max_length=500, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='objective',
            field=core.models.EAWTextField(help_text='Who is the intended audience for your talk? (Be specific, "Python users" is not a good answer). And what will the attendees get out of your talk? When they leave the room, what will they learn that they didn\'t know before? This is NOT made public and for REVIEW ONLY.', max_length=500, verbose_name='objective'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='abstract',
            field=core.models.EAWTextField(help_text='The overview of what the talk is about. If the talk assume some domain knowledge please state it here. If your talk is accepted, this will be displayed on both the website and the handbook. Should be one paragraph.', max_length=500, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='objective',
            field=core.models.EAWTextField(help_text='Who is the intended audience for your talk? (Be specific, "Python users" is not a good answer). And what will the attendees get out of your talk? When they leave the room, what will they learn that they didn\'t know before? This is NOT made public and for REVIEW ONLY.', max_length=500, verbose_name='objective'),
        ),
    ]
