# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 16:37
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_auto_20160222_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='abstract',
            field=core.models.EAWTextField(help_text='The overview of what the talk is about. If the talk assume some domain knowledge please state it here. If your talk is accepted, this will be displayed on both the website and the handbook. Should be one paragraph.', max_length=1000, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='detailed_description',
            field=models.TextField(blank=True, help_text="Try not be too lengthy to scare away reviewers or potential audience. A comfortable length is less than 2000 characters (or about 1200 Chinese characters). Since most reviewers may not understand the topic as deep as you do, including related links to the talk topic will help reviewers understand the proposal. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='objective',
            field=core.models.EAWTextField(help_text='Who is the intended audience for your talk? (Be specific, "Python users" is not a good answer). And what will the attendees get out of your talk? When they leave the room, what will they learn that they didn\'t know before? This is NOT made public and for REVIEW ONLY.', max_length=1000, verbose_name='objective'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='abstract',
            field=core.models.EAWTextField(help_text='The overview of what the talk is about. If the talk assume some domain knowledge please state it here. If your talk is accepted, this will be displayed on both the website and the handbook. Should be one paragraph.', max_length=1000, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='detailed_description',
            field=models.TextField(blank=True, help_text="Try not be too lengthy to scare away reviewers or potential audience. A comfortable length is less than 2000 characters (or about 1200 Chinese characters). Since most reviewers may not understand the topic as deep as you do, including related links to the talk topic will help reviewers understand the proposal. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='objective',
            field=core.models.EAWTextField(help_text='Who is the intended audience for your talk? (Be specific, "Python users" is not a good answer). And what will the attendees get out of your talk? When they leave the room, what will they learn that they didn\'t know before? This is NOT made public and for REVIEW ONLY.', max_length=1000, verbose_name='objective'),
        ),
    ]
