# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_auto_20160227_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='result',
            field=models.IntegerField(choices=[(0, 'Undecided'), (1, 'Accepted'), (2, 'Rejected')], db_index=True, default=0, verbose_name='review result'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='result',
            field=models.IntegerField(choices=[(0, 'Undecided'), (1, 'Accepted'), (2, 'Rejected')], db_index=True, default=0, verbose_name='review result'),
        ),
    ]
