# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0023_auto_20160305_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkproposal',
            name='result',
        ),
        migrations.RemoveField(
            model_name='tutorialproposal',
            name='result',
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='accepted',
            field=models.NullBooleanField(choices=[(None, '----------'), (True, 'Accepted'), (False, 'Rejected')], db_index=True, default=None, verbose_name='accepted'),
        ),
    ]
