# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0027_auto_20160426_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016')], default='pycontw-2016', verbose_name='conference'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016')], default='pycontw-2016', verbose_name='conference'),
        ),
    ]
