# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0028_auto_20161219_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalspeaker',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016')], default='pycontw-2016', verbose_name='conference'),
        ),
    ]
