# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0031_auto_20170129_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='outline',
            field=models.TextField(blank=True, help_text="<p><a href='#' data-toggle='modal' data-target='#proposalFieldExampleModal' data-content='outline'>Proposal Examples</a></p>How the talk will be arranged. It is highly recommended to attach the estimated time length for each sections in the talk. Talks in favor of 45min should have a fallback plan about how to shrink the content into a 30min one. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.This is NOT made public and for REVIEW ONLY.", verbose_name='outline'),
        ),
    ]
