# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0031_auto_20170129_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='detailed_description',
            field=models.TextField(blank=True, help_text="<p><a href='#' data-toggle='modal' data-target='#proposalFieldExampleModal'data-content='detailed description'>Proposal Examples</a></p>Try not be too lengthy to scare away reviewers or potential audience. A comfortable length is less than 2000 characters (or about 1200 Chinese characters). Since most reviewers may not understand the topic as deep as you do, including related links to the talk topic will help reviewers understand the proposal. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank' rel='noopener'>Markdown</a>.", verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='outline',
            field=models.TextField(blank=True, help_text="<p><a href='#' data-toggle='modal' data-target='#proposalFieldExampleModal' data-content='outline'>Proposal Examples</a></p>How the talk will be arranged. It is highly recommended to attach the estimated time length for each sections in the talk. Talks in favor of 45min should have a fallback plan about how to shrink the content into a 25min one. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank' rel='noopener'>Markdown</a>.This is NOT made public and for REVIEW ONLY.", verbose_name='outline'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='recording_policy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text="Whether you agree to give permission to PyCon Taiwan to record, edit, and release audio and video of your presentation. More information can be found at <a href='/en/speaking/recording/' target='_blank' rel='noopener'>Recording Release</a> page.", verbose_name='recording policy'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='supplementary',
            field=models.TextField(blank=True, default='', help_text="Anything else you'd like the program committee to know when making their selection: your past speaking experience, community experience, etc. This is NOT made public and for REVIEW ONLY. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank' rel='noopener'>Markdown</a>.", verbose_name='supplementary'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='detailed_description',
            field=models.TextField(blank=True, help_text="<p><a href='#' data-toggle='modal' data-target='#proposalFieldExampleModal'data-content='detailed description'>Proposal Examples</a></p>Try not be too lengthy to scare away reviewers or potential audience. A comfortable length is less than 2000 characters (or about 1200 Chinese characters). Since most reviewers may not understand the topic as deep as you do, including related links to the talk topic will help reviewers understand the proposal. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank' rel='noopener'>Markdown</a>.", verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='outline',
            field=models.TextField(blank=True, help_text="How the tutorial will be arranged. You should enumerate over each section in your talk and attach each section with the estimated time length. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank' rel='noopener'>Markdown</a>.This is NOT made public and for REVIEW ONLY.", verbose_name='outline'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='recording_policy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text="Whether you agree to give permission to PyCon Taiwan to record, edit, and release audio and video of your presentation. More information can be found at <a href='/en/speaking/recording/' target='_blank' rel='noopener'>Recording Release</a> page.", verbose_name='recording policy'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='supplementary',
            field=models.TextField(blank=True, default='', help_text="Anything else you'd like the program committee to know when making their selection: your past speaking experience, community experience, etc. This is NOT made public and for REVIEW ONLY. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank' rel='noopener'>Markdown</a>.", verbose_name='supplementary'),
        ),
    ]
