# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-07-10 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0038_add_new_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialproposal',
            name='accepted',
            field=models.NullBooleanField(choices=[(None, '----------'), (True, 'Accepted'), (False, 'Rejected')], db_index=True, default=None, verbose_name='accepted'),
        ),
    ]
