# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-09-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0039_tutorialproposal_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='slido_embed_link',
            field=models.URLField(blank=True, default='', verbose_name='slido embed link'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='slido_embed_link',
            field=models.URLField(blank=True, default='', verbose_name='slido embed link'),
        ),
    ]
