# Generated by Django 3.0.3 on 2020-02-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0041_auto_20200223_2331'),
        ('proposals', '0041_auto_20200223_1659'),
    ]

    operations = [
    ]
