# Generated by Django 3.0.3 on 2020-03-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0045_auto_20200318_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='category',
            field=models.CharField(choices=[('APPL', 'Application'), ('PRAC', 'Best Practices & Patterns'), ('COM', 'Community'), ('DB', 'Databases'), ('DATA', 'Data Analysis'), ('EDU', 'Education'), ('EMBED', 'Embedded Systems'), ('FIN', 'FinTech'), ('IOT', 'Internet of Things'), ('GAME', 'Gaming'), ('GRAPH', 'Graphics'), ('ML', 'Machine Learning'), ('NLP', 'Natural Language Processing'), ('CORE', 'Python Core (language, stdlib, etc.)'), ('TOOL', 'Project Tooling'), ('SCI', 'Science'), ('SEC', 'Security'), ('ADMIN', 'Systems Administration'), ('TEST', 'Testing'), ('WEB', 'Web Frameworks'), ('OTHER', 'Other')], max_length=5, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='category',
            field=models.CharField(choices=[('APPL', 'Application'), ('PRAC', 'Best Practices & Patterns'), ('COM', 'Community'), ('DB', 'Databases'), ('DATA', 'Data Analysis'), ('EDU', 'Education'), ('EMBED', 'Embedded Systems'), ('FIN', 'FinTech'), ('IOT', 'Internet of Things'), ('GAME', 'Gaming'), ('GRAPH', 'Graphics'), ('ML', 'Machine Learning'), ('NLP', 'Natural Language Processing'), ('CORE', 'Python Core (language, stdlib, etc.)'), ('TOOL', 'Project Tooling'), ('SCI', 'Science'), ('SEC', 'Security'), ('ADMIN', 'Systems Administration'), ('TEST', 'Testing'), ('WEB', 'Web Frameworks'), ('OTHER', 'Other')], max_length=5, verbose_name='category'),
        ),
    ]
