# Generated by Django 3.0.7 on 2021-01-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0048_auto_20210131_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='first_time_speaker',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='first time speaker'),
        ),
    ]
