# Generated by Django 3.0.7 on 2021-01-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0049_talkproposal_first_time_speaker'),
        ('proposals', '0048_auto_20210130_2309'),
    ]

    operations = [
    ]
