# Generated by Django 3.1.7 on 2021-09-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0051_auto_20210302_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='hackmd_embed_link',
            field=models.URLField(blank=True, default='', verbose_name='HackMD embed link'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='hackmd_embed_link',
            field=models.URLField(blank=True, default='', verbose_name='HackMD embed link'),
        ),
    ]
