# Generated by Django 3.1.7 on 2022-02-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0052_auto_20210930_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='living_in_taiwan',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='living in taiwan'),
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='pre_recorded_policy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='agree pre-recorded proposal'),
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='prefer_time',
            field=models.CharField(choices=[('DAY_ONE_MORNING', 'Day 1 morning'), ('DAY_ONE_AFTERNOON', 'Day 1 afternoon'), ('DAY_TWO_MORNING', 'Day 2 morning'), ('DAY_TWO_AFTERNOON', 'Day 2 afternoon')], default='', max_length=32, verbose_name='prefer event time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='living_in_taiwan',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='living in taiwan'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='pre_recorded_policy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='agree pre-recorded proposal'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='prefer_time',
            field=models.CharField(choices=[('DAY_ONE_MORNING', 'Day 1 morning'), ('DAY_ONE_AFTERNOON', 'Day 1 afternoon'), ('DAY_TWO_MORNING', 'Day 2 morning'), ('DAY_TWO_AFTERNOON', 'Day 2 afternoon')], default='', max_length=32, verbose_name='prefer event time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='language',
            field=models.CharField(choices=[('ENEN', 'English talk'), ('ZHEN', 'Chinese talk w. English slides'), ('ZHZH', 'Chinese talk w. Chinese slides')], max_length=4, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='language',
            field=models.CharField(choices=[('ENEN', 'English talk'), ('ZHEN', 'Chinese talk w. English slides'), ('ZHZH', 'Chinese talk w. Chinese slides')], max_length=4, verbose_name='language'),
        ),
    ]
