# Generated by Django 3.1.7 on 2022-02-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0053_auto_20220220_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkproposal',
            name='remoting_policy',
        ),
        migrations.RemoveField(
            model_name='tutorialproposal',
            name='remoting_policy',
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='talk_language',
            field=models.CharField(default='', max_length=32, verbose_name='Talk language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='talk_language',
            field=models.CharField(default='', max_length=32, verbose_name='Talk language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalspeaker',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020'), ('pycontw-2021', 'PyCon Taiwan 2021'), ('pycontw-2022', 'PyCon Taiwan 2022')], default='pycontw-2022', verbose_name='conference'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020'), ('pycontw-2021', 'PyCon Taiwan 2021'), ('pycontw-2022', 'PyCon Taiwan 2022')], default='pycontw-2022', verbose_name='conference'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='duration',
            field=models.CharField(max_length=6, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='language',
            field=models.CharField(choices=[('ENEN', 'English talk'), ('NONEN', 'non-English talk w. English slides')], max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='living_in_taiwan',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='living in Taiwan'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='prefer_time',
            field=models.CharField(choices=[('DAY_ONE_MORNING', 'Day 1, September 3rd, 2022 Morning'), ('DAY_ONE_AFTERNOON', 'Day 1, September 3rd, 2022 Afternoon'), ('DAY_TWO_MORNING', 'Day 2, September 4th, 2022 Morning'), ('DAY_TWO_AFTERNOON', 'Day 2, September 4th, 2022 Afternoon')], max_length=32, verbose_name='prefer event time'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020'), ('pycontw-2021', 'PyCon Taiwan 2021'), ('pycontw-2022', 'PyCon Taiwan 2022')], default='pycontw-2022', verbose_name='conference'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='duration',
            field=models.CharField(choices=[('1.5hr', '1.5hr')], default='1.5hr', max_length=7, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='language',
            field=models.CharField(choices=[('ENEN', 'English talk'), ('NONEN', 'non-English talk w. English slides')], max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='living_in_taiwan',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='living in Taiwan'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='prefer_time',
            field=models.CharField(choices=[('DAY_ONE_MORNING', 'Day 1, September 3rd, 2022 Morning'), ('DAY_ONE_AFTERNOON', 'Day 1, September 3rd, 2022 Afternoon'), ('DAY_TWO_MORNING', 'Day 2, September 4th, 2022 Morning'), ('DAY_TWO_AFTERNOON', 'Day 2, September 4th, 2022 Afternoon')], max_length=32, verbose_name='prefer event time'),
        ),
    ]
