# Generated by Django 3.1.7 on 2023-01-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0056_remove_pre_recorded_policy_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='prefer_time',
            field=models.CharField(choices=[('DAY_ONE_MORNING', 'Day 1, September 2nd, 2023 Morning'), ('DAY_ONE_AFTERNOON', 'Day 1, September 2nd, 2023 Afternoon'), ('DAY_TWO_MORNING', 'Day 2, September 3rd, 2023 Morning'), ('DAY_TWO_AFTERNOON', 'Day 2, September 3rd, 2023 Afternoon')], max_length=32, verbose_name='prefer event time'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='prefer_time',
            field=models.CharField(choices=[('DAY_ONE_MORNING', 'Day 1, September 2nd, 2023 Morning'), ('DAY_ONE_AFTERNOON', 'Day 1, September 2nd, 2023 Afternoon'), ('DAY_TWO_MORNING', 'Day 2, September 3rd, 2023 Morning'), ('DAY_TWO_AFTERNOON', 'Day 2, September 3rd, 2023 Afternoon')], max_length=32, verbose_name='prefer event time'),
        ),
    ]
