# Generated by Django 3.1.7 on 2023-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0058_alter_language_choices_remove_talk_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkproposal',
            name='willing_to_attend_in_person',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='attending PyCon TW in person'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='willing_to_attend_in_person',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='attending PyCon TW in person'),
        ),
    ]
