# Generated by Django 3.1.7 on 2023-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0059_add_willing_to_attend_in_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='first_time_speaker',
            field=models.BooleanField(choices=[(True, 'Yes, it is my first time speaking at PyCon Taiwan.'), (False, 'No, I have given talks at PyCon Taiwan in the past.')], default=False, verbose_name='first time speaker'),
        ),
    ]
