# Generated by Django 3.1.7 on 2024-02-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0063_auto_20240221_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkproposal',
            name='prefer_time',
        ),
        migrations.RemoveField(
            model_name='tutorialproposal',
            name='prefer_time',
        ),
    ]
