# Generated by Django 3.2.25 on 2025-03-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0064_auto_20240224_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalspeaker',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020'), ('pycontw-2021', 'PyCon Taiwan 2021'), ('pycontw-2022', 'PyCon Taiwan 2022'), ('pycontw-2023', 'PyCon Taiwan 2023'), ('pycontw-2024', 'PyCon Taiwan 2024'), ('pycontw-2025', 'PyCon Taiwan 2025')], default='pycontw-2025', verbose_name='conference'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020'), ('pycontw-2021', 'PyCon Taiwan 2021'), ('pycontw-2022', 'PyCon Taiwan 2022'), ('pycontw-2023', 'PyCon Taiwan 2023'), ('pycontw-2024', 'PyCon Taiwan 2024'), ('pycontw-2025', 'PyCon Taiwan 2025')], default='pycontw-2025', verbose_name='conference'),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020'), ('pycontw-2021', 'PyCon Taiwan 2021'), ('pycontw-2022', 'PyCon Taiwan 2022'), ('pycontw-2023', 'PyCon Taiwan 2023'), ('pycontw-2024', 'PyCon Taiwan 2024'), ('pycontw-2025', 'PyCon Taiwan 2025')], default='pycontw-2025', verbose_name='conference'),
        ),
        migrations.CreateModel(
            name='LLMReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020'), ('pycontw-2021', 'PyCon Taiwan 2021'), ('pycontw-2022', 'PyCon Taiwan 2022'), ('pycontw-2023', 'PyCon Taiwan 2023'), ('pycontw-2024', 'PyCon Taiwan 2024'), ('pycontw-2025', 'PyCon Taiwan 2025')], default='pycontw-2025', verbose_name='conference')),
                ('summary', models.TextField(verbose_name='AI-generated summary')),
                ('comment', models.TextField(verbose_name='AI-generated comment')),
                ('translated_summary', models.TextField(verbose_name='translated summary')),
                ('translated_comment', models.TextField(verbose_name='translated comment')),
                ('vote', models.CharField(choices=[('-1', '-1 (strong reject)'), ('-0', '-0 (weak reject)'), ('+0', '+0 (weak accept)'), ('+1', '+1 (strong accept)')], max_length=2, verbose_name='AI vote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_review', to='proposals.talkproposal', verbose_name='proposal')),
            ],
            options={
                'verbose_name': 'LLM review',
                'verbose_name_plural': 'LLM reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
