# Generated by Django 3.2.25 on 2025-04-09 18:09

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0065_auto_20250327_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmreview',
            name='category',
            field=models.CharField(choices=[('APPL', 'Application'), ('PRAC', 'Best Practices & Patterns'), ('COM', 'Community'), ('DB', 'Databases'), ('DATA', 'Data Analysis'), ('EDU', 'Education'), ('EMBED', 'Embedded Systems'), ('FIN', 'FinTech'), ('IOT', 'Internet of Things'), ('GAME', 'Gaming'), ('GRAPH', 'Graphics'), ('ML', 'Machine Learning'), ('NLP', 'Natural Language Processing'), ('CORE', 'Python Core (language, stdlib, etc.)'), ('TOOL', 'Project Tooling'), ('SCI', 'Science'), ('SEC', 'Security'), ('ADMIN', 'Systems Administration'), ('TEST', 'Testing'), ('WEB', 'Web Frameworks'), ('OTHER', 'Other')], default='APPL', max_length=5, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='llmreview',
            name='proposal',
            field=core.models.BigForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_review', to='proposals.talkproposal', unique=True, verbose_name='proposal'),
        ),
    ]
