# Generated by Django 3.2.25 on 2025-05-12 09:34

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0066_auto_20250410_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmreview',
            options={'ordering': ['proposal__title', 'stage', '-created_at'], 'verbose_name': 'LLM review', 'verbose_name_plural': 'LLM reviews'},
        ),
        migrations.AddField(
            model_name='llmreview',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('APPL', 'Application'), ('PRAC', 'Best Practices & Patterns'), ('COM', 'Community'), ('DB', 'Databases'), ('DATA', 'Data Analysis'), ('EDU', 'Education'), ('EMBED', 'Embedded Systems'), ('FIN', 'FinTech'), ('IOT', 'Internet of Things'), ('GAME', 'Gaming'), ('GRAPH', 'Graphics'), ('ML', 'Machine Learning'), ('NLP', 'Natural Language Processing'), ('CORE', 'Python Core (language, stdlib, etc.)'), ('TOOL', 'Project Tooling'), ('SCI', 'Science'), ('SEC', 'Security'), ('ADMIN', 'Systems Administration'), ('TEST', 'Testing'), ('WEB', 'Web Frameworks'), ('OTHER', 'Other')], max_length=5), blank=True, default=list, help_text='Select up to three categories for the proposal.', size=3, verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='llmreview',
            name='stage',
            field=models.CharField(choices=[('S1', 'Stage 1'), ('S2', 'Stage 2')], db_index=True, default='S1', max_length=2, verbose_name='review stage'),
        ),
        migrations.AddField(
            model_name='llmreview',
            name='stage_diff',
            field=models.TextField(blank=True, default='', help_text='Differences noted between stage 1 and stage 2 reviews, if applicable.', verbose_name='stage difference'),
        ),
        migrations.AddField(
            model_name='llmreview',
            name='translated_stage_diff',
            field=models.TextField(blank=True, default='', help_text='Translated differences noted between stage 1 and stage 2 reviews, if applicable.', verbose_name='translated stage difference'),
        ),
        migrations.AlterField(
            model_name='llmreview',
            name='proposal',
            field=core.models.BigForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_reviews', to='proposals.talkproposal', verbose_name='proposal'),
        ),
        migrations.AlterUniqueTogether(
            name='llmreview',
            unique_together={('proposal', 'stage')},
        ),
        migrations.RemoveField(
            model_name='llmreview',
            name='category',
        ),
    ]
