# Generated by Django 3.2.25 on 2025-08-18 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0067_auto_20250512_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmreview',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('APPL', 'Application'), ('PRAC', 'Best Practices & Patterns'), ('COM', 'Community'), ('DB', 'Databases'), ('DATA', 'Data Analysis'), ('EDU', 'Education'), ('EMBED', 'Embedded Systems'), ('FIN', 'FinTech'), ('IOT', 'Internet of Things'), ('GAME', 'Gaming'), ('GRAPH', 'Graphics'), ('ML', 'Machine Learning'), ('NLP', 'Natural Language Processing'), ('CORE', 'Python Core (language, stdlib, etc.)'), ('TOOL', 'Project Tooling'), ('SCI', 'Science'), ('SEC', 'Security'), ('ADMIN', 'Systems Administration'), ('TEST', 'Testing'), ('WEB', 'Web Frameworks'), ('OTHER', 'Other')], max_length=5), blank=True, default=list, size=3, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='llmreview',
            name='stage_diff',
            field=models.TextField(blank=True, default='', verbose_name='stage difference'),
        ),
        migrations.AlterField(
            model_name='llmreview',
            name='translated_stage_diff',
            field=models.TextField(blank=True, default='', verbose_name='translated stage difference'),
        ),
    ]
