# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0022_auto_20160227_1637'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('score', models.IntegerField(choices=[(4, '+1'), (3, '+0'), (2, '-0'), (1, '-1'), (0, 'Undecided')], default=0, verbose_name='Score')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.TalkProposal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
