# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 05:25
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160305_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-updated'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text="Comments to this proposal. This may be available for other reviewers in later review stages, and you can choose whether or not to disclose it to the proposal's submitter.", verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='note',
            field=models.TextField(blank=True, help_text='Personal notes about this proposal. You can use this field to record anything you like during the review process. We promise to never disclose them to anyone.', verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='review',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.TalkProposal', verbose_name='proposal'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=core.models.BigForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='reviewer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(choices=[(2, '+1'), (1, '+0'), (0, '----------'), (-1, '-0'), (-2, '-1')], default=0, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stage',
            field=models.IntegerField(default=1, verbose_name='stage'),
        ),
    ]
