# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_discloses_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stage',
            field=models.IntegerField(verbose_name='stage'),
        ),
    ]
