# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20160307_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated'),
        ),
    ]
