# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20160307_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(choices=[(2, '+1 (strong accept)'), (1, '+0 (weakly accept)'), (0, '----------'), (-1, '-0 (weakly reject)'), (-2, '-1 (strong reject)')], default=0, help_text='Your score to accept or reject this talk. More information about the scoring and acceptance criteria can be found at the google doc <a href="https://goo.gl/EPlUZx">Review Guideline</a>.', verbose_name='score'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('reviewer', 'stage', 'proposal')]),
        ),
    ]
