# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-19 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20160307_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vote',
            field=models.CharField(blank=True, choices=[('+1', '+1 (strong accept)'), ('+0', '+0 (weakly accept)'), ('−0', '-0 (weakly reject)'), ('−1', '-1 (strong reject)')], help_text='Your vote to accept or reject this talk. More information about the scoring and acceptance criteria can be found at the google doc <a href="https://goo.gl/EPlUZx" target="_blank">Review Guideline</a>.', max_length=2, verbose_name='vote'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(choices=[(2, '+1 (strong accept)'), (1, '+0 (weakly accept)'), (0, '----------'), (-1, '-0 (weakly reject)'), (-2, '-1 (strong reject)')], default=0, help_text='Your score to accept or reject this talk. More information about the scoring and acceptance criteria can be found at the google doc <a href="https://goo.gl/EPlUZx" target="_blank">Review Guideline</a>.', verbose_name='score'),
        ),
    ]
