# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20160326_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
