# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20151222_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twitter'),
        ),
    ]
