# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20151225_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(help_text='Describe yourself with 500 characters or less. There will be no formatting.', max_length=500, verbose_name='biography'),
        ),
    ]
