# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 13:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160122_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_id',
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_profile_url',
            field=models.URLField(blank=True, help_text="Link to your Facebook profile page. This will be shown when we display your public information. If you do not know what your profile page link is, click on <a href='https://www.facebook.com/me' target='_blank'>this link</a>, and copy-paste the URL of the page opened. Remember to log in to Facebook first!", verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, help_text='Your GitHub account, without the "@" sign. This will be shown when we display your public information.', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Not a valid GitHub account')], verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(blank=True, help_text='Your Twitter handle, without the "@" sign. This will be shown when we display your public information.', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Not a valid Twitter handle')], verbose_name='Twitter'),
        ),
    ]
