# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 05:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160122_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, help_text='Your GitHub account, without the "@" sign. This will be shown when we display your public information.', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Not a valid GitHub account')], verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(blank=True, help_text='Your Twitter handle, without the "@" sign. This will be shown when we display your public information.', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Not a valid Twitter handle')], verbose_name='Twitter'),
        ),
    ]
