# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160227_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_profile_url',
            field=models.URLField(blank=True, help_text="Link to your Facebook profile page. This will be shown when we display your public information. If you do not know what your profile page link is, click on <a href='https://www.facebook.com/me' target='_blank' rel='noopener'>this link</a>, and copy-paste the URL of the page opened. Remember to log in to Facebook first!", verbose_name='Facebook'),
        ),
    ]
