# Generated by Django 3.0.7 on 2021-02-26 14:48

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cocrecord_agreed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=core.models.EAWTextField(help_text='Describe yourself with 1000 characters or less. There will be no formatting.', max_length=1000, verbose_name='biography'),
        ),
    ]
