version: "3"

services:
  db:
    container_name: db_dev
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=pycontw2016
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpostgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready"
      start_period: 5s
      interval: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pycontw:
    container_name: pycontw_dev
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ..:/usr/local/app
      - node_modules:/usr/local/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:secretpostgres@db:5432/pycontw2016
      - SECRET_KEY=django-insecure-secret-key
    command: sleep infinity
    working_dir: /usr/local/app

volumes:
  postgres_data:
  node_modules: 