# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_keynoteevent_squashed_0007_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016')], default='pycontw-2016', verbose_name='conference'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016')], default='pycontw-2016', verbose_name='conference'),
        ),
        migrations.AddField(
            model_name='proposedtalkevent',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016')], default='pycontw-2016', verbose_name='conference'),
        ),
        migrations.AddField(
            model_name='sponsoredevent',
            name='conference',
            field=models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016')], default='pycontw-2016', verbose_name='conference'),
        ),
    ]
