# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_customevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(verbose_name='HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'get_latest_by': 'created_at',
            },
        ),
    ]
