# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 09:11
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170129_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredevent',
            name='abstract',
            field=core.models.EAWTextField(max_length=1000, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='sponsoredevent',
            name='detailed_description',
            field=models.TextField(blank=True, verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='sponsoredevent',
            name='python_level',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('EXPERIENCED', 'Experienced')], max_length=12, verbose_name='Python level'),
        ),
        migrations.AlterField(
            model_name='sponsoredevent',
            name='recording_policy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='recording policy'),
        ),
        migrations.AlterField(
            model_name='sponsoredevent',
            name='slide_link',
            field=models.URLField(blank=True, default='', verbose_name='slide link'),
        ),
    ]
