# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_sponsoredevent_last_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='break_event',
            field=models.BooleanField(default=False, help_text='Whether this event is displays as a break. A break can be visually distinguished from "real" conference sessions, such as keynotes, talks, etc.', verbose_name='is break event'),
        ),
    ]
