# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_customevent_break_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('5-r1', 'R1'), ('6-r2', 'R2'), ('1-r3', 'R3'), ('7-r4', 'R4')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('5-r1', 'R1'), ('6-r2', 'R2'), ('1-r3', 'R3'), ('7-r4', 'R4')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='proposedtalkevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('5-r1', 'R1'), ('6-r2', 'R2'), ('1-r3', 'R3'), ('7-r4', 'R4')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='sponsoredevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('5-r1', 'R1'), ('6-r2', 'R2'), ('1-r3', 'R3'), ('7-r4', 'R4')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
    ]
