# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-07-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_proposedtutorialevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtutorialevent',
            name='registration_link',
            field=models.URLField(blank=True, default='', verbose_name='registration link'),
        ),
    ]
