# Generated by Django 3.0.7 on 2020-08-23 15:28

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0018_openrole'),
        ('events', '0024_auto_20200319_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListingsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.SlugField(choices=[('pycontw-2016', 'PyCon Taiwan 2016'), ('pycontw-2017', 'PyCon Taiwan 2017'), ('pycontw-2018', 'PyCon Taiwan 2018'), ('pycontw-2019', 'PyCon Taiwan 2019'), ('pycontw-2020', 'PyCon Taiwan 2020')], default='pycontw-2020', verbose_name='conference')),
                ('location', models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('5-r1', 'R1'), ('6-r2', 'R2'), ('1-r3', 'R3'), ('7-r4', 'R4')], db_index=True, max_length=6, null=True, verbose_name='location')),
                ('begin_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begined_joblistingsevent_set', to='events.Time', verbose_name='begin time')),
                ('end_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ended_joblistingsevent_set', to='events.Time', verbose_name='end time')),
                ('sponsor', core.models.BigForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.Sponsor', verbose_name='sponsor')),
            ],
            options={
                'verbose_name': 'Job Listings',
                'verbose_name_plural': 'Job Listings',
            },
        ),
    ]
