# Generated by Django 3.0.7 on 2020-08-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20200828_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R1, R2, R3'), ('4-r0', 'R1'), ('5-r1', 'R2'), ('6-r2', 'R3'), ('1-r3', 'Multifunction room'), ('7-r4', 'Goodideas Studio'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='joblistingsevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R1, R2, R3'), ('4-r0', 'R1'), ('5-r1', 'R2'), ('6-r2', 'R3'), ('1-r3', 'Multifunction room'), ('7-r4', 'Goodideas Studio'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R1, R2, R3'), ('4-r0', 'R1'), ('5-r1', 'R2'), ('6-r2', 'R3'), ('1-r3', 'Multifunction room'), ('7-r4', 'Goodideas Studio'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='proposedtalkevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R1, R2, R3'), ('4-r0', 'R1'), ('5-r1', 'R2'), ('6-r2', 'R3'), ('1-r3', 'Multifunction room'), ('7-r4', 'Goodideas Studio'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='proposedtutorialevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R1, R2, R3'), ('4-r0', 'R1'), ('5-r1', 'R2'), ('6-r2', 'R3'), ('1-r3', 'Multifunction room'), ('7-r4', 'Goodideas Studio'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='sponsoredevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R1, R2, R3'), ('4-r0', 'R1'), ('5-r1', 'R2'), ('6-r2', 'R3'), ('1-r3', 'Multifunction room'), ('7-r4', 'Goodideas Studio'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
    ]
