# Generated by Django 3.0.3 on 2020-09-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20200829_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='event description'),
        ),
        migrations.AddField(
            model_name='customevent',
            name='link_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='link path'),
        ),
    ]
