# Generated by Django 3.0.3 on 2020-09-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20200902_0343'),
        ('events', '0028_auto_20200902_1549'),
    ]

    operations = [
    ]
