# Generated by Django 3.0.3 on 2020-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20200902_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtalkevent',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='is remote'),
        ),
    ]
