# Generated by Django 3.0.3 on 2020-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_proposedtalkevent_is_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='keynoteevent',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='is remote'),
        ),
    ]
