# Generated by Django 3.0.3 on 2020-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_keynoteevent_is_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtutorialevent',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='is remote'),
        ),
    ]
