# Generated by Django 3.0.7 on 2021-01-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20210130_2309'),
        ('events', '0033_auto_20210131_1548'),
    ]

    operations = [
    ]
