# Generated by Django 3.0.7 on 2021-03-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_merge_20210131_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredevent',
            name='live_stream_policy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='live stream policy'),
        ),
    ]
