# Generated by Django 3.1.7 on 2021-06-19 13:47

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_sponsoredevent_live_stream_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='keynoteevent',
            name='session_description',
            field=models.TextField(verbose_name='keynote session description'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='session_description_en_us',
            field=models.TextField(verbose_name='keynote session description'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='session_description_zh_hant',
            field=models.TextField(verbose_name='keynote session description'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='session_slides',
            field=models.URLField(blank=True, verbose_name='session slides'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='session_title',
            field=models.CharField(max_length=140, verbose_name='keynote session title'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='session_title_en_us',
            field=models.CharField(max_length=140, verbose_name='keynote session title'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='session_title_zh_hant',
            field=models.CharField(max_length=140, verbose_name='keynote session title'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='slido',
            field=models.URLField(blank=True, verbose_name='slido'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='social_github',
            field=models.URLField(blank=True, verbose_name='social github'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='social_linkedin',
            field=models.URLField(blank=True, verbose_name='social linkedin'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='social_twitter',
            field=models.URLField(blank=True, verbose_name='social twitter'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='speaker_bio',
            field=models.TextField(verbose_name='speaker bio'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='speaker_bio_en_us',
            field=models.TextField(verbose_name='speaker bio'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='speaker_bio_zh_hant',
            field=models.TextField(verbose_name='speaker bio'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='speaker_name_en_us',
            field=models.CharField(max_length=100, verbose_name='speaker name'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='speaker_name_zh_hant',
            field=models.CharField(max_length=100, verbose_name='speaker name'),
        ),
        migrations.AddField(
            model_name='keynoteevent',
            name='speaker_photo',
            field=models.ImageField(help_text="Raster format of the speaker's photo, e.g. PNG, JPEG.",
                                    upload_to=events.models.photo_upload_to, verbose_name='speaker photo'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='speaker_name',
            field=models.CharField(max_length=100, verbose_name='speaker name'),
        ),
    ]
