# Generated by Django 3.1.7 on 2021-06-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_alter_keynoteevent_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keynoteevent',
            name='session_description_en_us',
            field=models.TextField(null=True, verbose_name='keynote session description'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='session_description_zh_hant',
            field=models.TextField(null=True, verbose_name='keynote session description'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='session_title_en_us',
            field=models.CharField(max_length=140, null=True, verbose_name='keynote session title'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='session_title_zh_hant',
            field=models.CharField(max_length=140, null=True, verbose_name='keynote session title'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='speaker_bio_en_us',
            field=models.TextField(null=True, verbose_name='speaker bio'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='speaker_bio_zh_hant',
            field=models.TextField(null=True, verbose_name='speaker bio'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='speaker_name_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name='speaker name'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='speaker_name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='speaker name'),
        ),
    ]
