# Generated by Django 3.1.7 on 2021-07-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20210718_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtalkevent',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='youtube id'),
        ),
        migrations.AddField(
            model_name='sponsoredevent',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='youtube id'),
        ),
    ]
