# Generated by Django 3.1.7 on 2021-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_auto_20210731_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='keynoteevent',
            name='hackmd_embed_link',
            field=models.URLField(blank=True, default='', verbose_name='HackMD embed link'),
        ),
        migrations.AddField(
            model_name='sponsoredevent',
            name='hackmd_embed_link',
            field=models.URLField(blank=True, default='', verbose_name='HackMD embed link'),
        ),
    ]
