# Generated by Django 3.1.7 on 2021-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20210930_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedtutorialevent',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='youtube id'),
        ),
    ]
