# Generated by Django 3.1.7 on 2022-02-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20220227_1140'),
        ('events', '0040_proposedtutorialevent_youtube_id'),
    ]

    operations = [
    ]
