# Generated by Django 3.1.7 on 2022-08-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_auto_20220711_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('4-r0-1', 'R0_1'), ('4-r0-2', 'R0_2'), ('5-r1', 'R1'), ('5-r1-1', 'R1_1'), ('5-r1-2', 'R1_2'), ('6-r2', 'R2'), ('6-r2-1', 'R2_1'), ('6-r2-2', 'R2_2'), ('1-r3', 'R3'), ('7-r4', 'Open Space'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='joblistingsevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('4-r0-1', 'R0_1'), ('4-r0-2', 'R0_2'), ('5-r1', 'R1'), ('5-r1-1', 'R1_1'), ('5-r1-2', 'R1_2'), ('6-r2', 'R2'), ('6-r2-1', 'R2_1'), ('6-r2-2', 'R2_2'), ('1-r3', 'R3'), ('7-r4', 'Open Space'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='keynoteevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('4-r0-1', 'R0_1'), ('4-r0-2', 'R0_2'), ('5-r1', 'R1'), ('5-r1-1', 'R1_1'), ('5-r1-2', 'R1_2'), ('6-r2', 'R2'), ('6-r2-1', 'R2_1'), ('6-r2-2', 'R2_2'), ('1-r3', 'R3'), ('7-r4', 'Open Space'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='proposedtalkevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('4-r0-1', 'R0_1'), ('4-r0-2', 'R0_2'), ('5-r1', 'R1'), ('5-r1-1', 'R1_1'), ('5-r1-2', 'R1_2'), ('6-r2', 'R2'), ('6-r2-1', 'R2_1'), ('6-r2-2', 'R2_2'), ('1-r3', 'R3'), ('7-r4', 'Open Space'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='proposedtutorialevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('4-r0-1', 'R0_1'), ('4-r0-2', 'R0_2'), ('5-r1', 'R1'), ('5-r1-1', 'R1_1'), ('5-r1-2', 'R1_2'), ('6-r2', 'R2'), ('6-r2-1', 'R2_1'), ('6-r2-2', 'R2_2'), ('1-r3', 'R3'), ('7-r4', 'Open Space'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='sponsoredevent',
            name='location',
            field=models.CharField(blank=True, choices=[('2-all', 'All rooms'), ('3-r012', 'R0, R1, R2'), ('4-r0', 'R0'), ('4-r0-1', 'R0_1'), ('4-r0-2', 'R0_2'), ('5-r1', 'R1'), ('5-r1-1', 'R1_1'), ('5-r1-2', 'R1_2'), ('6-r2', 'R2'), ('6-r2-1', 'R2_1'), ('6-r2-2', 'R2_2'), ('1-r3', 'R3'), ('7-r4', 'Open Space'), ('8-oth', 'Other')], db_index=True, max_length=6, null=True, verbose_name='location'),
        ),
    ]
