# Generated by Django 3.1.7 on 2023-02-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_add_willing_to_attend_in_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsoredevent',
            old_name='willing_to_attend_in_person',
            new_name='attend_in_person',
        ),
    ]
