# Generated by Django 3.1.7 on 2023-03-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_rename_willing_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
