# Generated by Django 3.1.7 on 2024-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_auto_20240127_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredevent',
            name='prefer_time',
            field=models.CharField(choices=[('DAY_ONE_MORNING', 'Day 1, September 21st, 2024 Morning'), ('DAY_ONE_AFTERNOON', 'Day 1, September 21st, 2024 Afternoon'), ('DAY_TWO_MORNING', 'Day 2, September 22nd, 2024 Morning'), ('DAY_TWO_AFTERNOON', 'Day 2, September 22nd, 2024 Afternoon')], max_length=32, verbose_name='prefer event time'),
        ),
    ]
