# Generated by Django 3.1.7 on 2024-02-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_auto_20240221_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsoredevent',
            name='prefer_time',
        ),
    ]
